# Generated by Django 5.2 on 2025-04-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_at',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('beach', 'Beach'), ('city', 'City'), ('hiking', 'Hiking'), ('business', 'Business'), ('snow', 'Snow / Ski'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
