# Generated by Django 5.2 on 2025-04-10 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_created_at_trip_trip_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_packed', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='trips.trip')),
            ],
        ),
    ]
