# Generated by Django 5.2 on 2025-04-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_packingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='manually_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
